# Generated by Django 4.2.11 on 2024-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_method',
            field=models.TextField(default=''),
        ),
    ]
