# Generated by Django 4.2.11 on 2024-05-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_recipe_recipe_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_method',
            new_name='blurb',
        ),
    ]
