# Generated by Django 4.2.11 on 2024-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_content_recipe_recipe_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
