# Generated by Django 4.2.11 on 2024-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_comment_comment_content'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='blog.recipe'),
        ),
    ]
