# Generated by Django 4.2.11 on 2024-05-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
